/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adproyecto.libroReceta;

import com.mycompany.adproyecto.Main;
import com.mycompany.adproyecto.libroReceta.IDAO.BinaryDAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.BufferedDAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.DOMDAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.RADAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.object.ObjectDAOLibroRecetas;
import com.mycompany.adproyecto.receta.IDAO.BinaryDAOReceta;
import com.mycompany.adproyecto.receta.IDAO.BufferedDAOReceta;
import com.mycompany.adproyecto.receta.IDAO.DOMDAOReceta;
import com.mycompany.adproyecto.receta.IDAO.RADAOReceta;
import com.mycompany.adproyecto.receta.IDAO.object.ObjectDAOReceta;
import com.mycompany.adproyecto.receta.Receta;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.TimeZone;
import javax.swing.JOptionPane;

/**
 *
 * @author mrpox
 */
public class LibroRecetasDelete extends javax.swing.JFrame {

    private BufferedDAOReceta bR;
    private BinaryDAOReceta dR;
    private ObjectDAOReceta oR;
    private char typeData;
    private File file;
    private File fileR;
    private RADAOReceta rR;
    private final SimpleDateFormat sdf;
    private BufferedDAOLibroRecetas bLR;
    private BinaryDAOLibroRecetas dLR;
    private ObjectDAOLibroRecetas oLR;
    private RADAOLibroRecetas rLR;
    private DOMDAOLibroRecetas domLR;
    private DOMDAOReceta domR;

    /**
     * Creates new form LibroRecetasDelete
     */
    public LibroRecetasDelete() {
        super("LIBRO DE RECETAS DELETE");
        initComponents();
        this.setLocationRelativeTo(null);
        this.sdf = new SimpleDateFormat("E MMM dd HH:mm:ss z yyyy", Locale.ENGLISH);
        this.sdf.setTimeZone(TimeZone.getTimeZone("Europe/Paris"));
        this.setResizable(false);
    }

    public void setTypeData(char typeData) {
        this.typeData = typeData;
    }

    public void setFile(File file) {
        this.file = file;
    }

    public void setFileR(File fileR) {
        this.fileR = fileR;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        textIsbn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("VOLVER");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        textIsbn.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("ISBN del Libro de Recetas a borrar:");

        buttonBorrar.setText("BORRAR");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(textIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addComponent(buttonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        // TODO add your handling code here:
        ArrayList<Receta> listaRecetas = new ArrayList<>();
        LibroRecetas libroRAux = null;
        Receta auxUpdate = null;
        int isbnNum;
        if (textIsbn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ALGUN CAMPO REQUERIDO ES INCORRECTO",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!textIsbn.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "SOLO SE ACEPTA VALOR NUMÉRICO EN EL CAMPO ISBN",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        isbnNum = Integer.parseInt(textIsbn.getText());
        switch (typeData) {
            case 'B' -> {
                bLR = new BufferedDAOLibroRecetas(file.getAbsolutePath());
                bR = new BufferedDAOReceta(fileR.getAbsolutePath());
                libroRAux = bLR.consultaId(isbnNum);
                if (libroRAux != null) {
                    if (bLR.baja(libroRAux) != null) {
                        JOptionPane.showMessageDialog(null, "BORRADO DEL LIBRO DE RECETAS CORRECTA",
                                "OK", JOptionPane.INFORMATION_MESSAGE);
                        if (fileR.length() > 0) {
                            listaRecetas = bR.consultaAll();
                            for (Receta next : listaRecetas) {
                                if (next.getIdReceta() == isbnNum) {
                                    auxUpdate = next;
                                    auxUpdate.setIdLibro(0);
                                    bR.modificar(next, auxUpdate);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR EN EL BORRADO",
                                "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL ISBN DEL LIBRO A BORRAR NO SE HA ENCONTRADO",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            case 'D' -> {
                dLR = new BinaryDAOLibroRecetas(file.getAbsolutePath());
                dR = new BinaryDAOReceta(fileR.getAbsolutePath());
                libroRAux = dLR.consultaId(isbnNum);
                if (libroRAux != null) {
                    if (dLR.baja(libroRAux) != null) {
                        JOptionPane.showMessageDialog(null, "BORRADO DEL LIBRO DE RECETAS CORRECTA",
                                "OK", JOptionPane.INFORMATION_MESSAGE);
                        if (fileR.length() > 0) {
                            listaRecetas = dR.consultaAll();
                            for (Receta next : listaRecetas) {
                                if (next.getIdReceta() == isbnNum) {
                                    auxUpdate = next;
                                    auxUpdate.setIdLibro(0);
                                    dR.modificar(next, auxUpdate);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR EN EL BORRADO",
                                "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL ISBN DEL LIBRO A BORRAR NO SE HA ENCONTRADO",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            case 'O' -> {
                oLR = new ObjectDAOLibroRecetas(file.getAbsolutePath());
                oR = new ObjectDAOReceta(fileR.getAbsolutePath());
                libroRAux = oLR.consultaId(isbnNum);
                if (libroRAux != null) {
                    if (oLR.baja(libroRAux) != null) {
                        JOptionPane.showMessageDialog(null, "BORRADO DEL LIBRO DE RECETAS CORRECTA",
                                "OK", JOptionPane.INFORMATION_MESSAGE);
                        if (fileR.length() > 0) {
                            listaRecetas = oR.consultaAll();
                            for (Receta next : listaRecetas) {
                                if (next.getIdReceta() == isbnNum) {
                                    auxUpdate = next;
                                    auxUpdate.setIdLibro(0);
                                    oR.modificar(next, auxUpdate);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR EN EL BORRADO",
                                "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL ISBN DEL LIBRO A BORRAR NO SE HA ENCONTRADO",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            case 'R' -> {
                rLR = new RADAOLibroRecetas(file.getAbsolutePath());
                rR = new RADAOReceta(fileR.getAbsolutePath());
                libroRAux = rLR.consultaId(isbnNum);
                if (libroRAux != null) {
                    if (rLR.baja(libroRAux) != null) {
                        JOptionPane.showMessageDialog(null, "BORRADO DEL LIBRO DE RECETAS CORRECTA",
                                "OK", JOptionPane.INFORMATION_MESSAGE);
                        if (fileR.length() > 0) {
                            listaRecetas = rR.consultaAll();
                            for (Receta next : listaRecetas) {
                                if (next.getIdReceta() == isbnNum) {
                                    auxUpdate = next;
                                    auxUpdate.setIdLibro(0);
                                    rR.modificar(next, auxUpdate);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR EN EL BORRADO",
                                "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL ISBN DEL LIBRO A BORRAR NO SE HA ENCONTRADO",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            case 'X' -> {
                domLR = new DOMDAOLibroRecetas(file.getAbsolutePath());
                domR = new DOMDAOReceta(fileR.getAbsolutePath());
                libroRAux = domLR.consultaId(isbnNum);
                if (libroRAux != null) {
                    if (domLR.baja(libroRAux) != null) {
                        JOptionPane.showMessageDialog(null, "BORRADO DEL LIBRO DE RECETAS CORRECTA",
                                "OK", JOptionPane.INFORMATION_MESSAGE);
                        if (fileR.length() > 0) {
                            listaRecetas = domR.consultaAll();

                            for (Receta next : listaRecetas) {
                                if (next.getIdReceta() == isbnNum) {
                                    auxUpdate = next;
                                    auxUpdate.setIdLibro(0);
                                    domR.modificar(next, auxUpdate);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR EN EL BORRADO",
                                "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL ISBN DEL LIBRO A BORRAR NO SE HA ENCONTRADO",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_buttonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroRecetasDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroRecetasDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroRecetasDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroRecetasDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibroRecetasDelete().setVisible(true);
            }
        });
    }

    private boolean testLibroIfExists(LibroRecetas libroRAux) {
        return libroRAux != null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textIsbn;
    // End of variables declaration//GEN-END:variables
}
