/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adproyecto.libroReceta;

import com.mycompany.adproyecto.Main;
import com.mycompany.adproyecto.libroReceta.IDAO.BinaryDAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.BufferedDAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.DOMDAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.RADAOLibroRecetas;
import com.mycompany.adproyecto.libroReceta.IDAO.object.ObjectDAOLibroRecetas;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mrpox
 */
public class LibroRecetasRead extends javax.swing.JFrame {

    private BufferedDAOLibroRecetas bLR;
    private BinaryDAOLibroRecetas dLR;
    private ObjectDAOLibroRecetas oLR;
    private File file;
    private RADAOLibroRecetas rLR;
    private char typeData;
    private DOMDAOLibroRecetas domLR;

    /**
     * Creates new form LibroRecetasRead
     */
    public LibroRecetasRead() {
        super("LIBRO DE RECETAS READ");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void setFile(File file) {
        this.file = file;
    }

    public void setTypeData(char typeData) {
        this.typeData = typeData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarButtonISBN = new javax.swing.JButton();
        buscarButtonAll = new javax.swing.JButton();
        textConsultaAll = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        textResultados = new javax.swing.JLabel();
        textBusqueda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buscarButtonISBN.setText("BUSCAR");
        buscarButtonISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonISBNActionPerformed(evt);
            }
        });

        buscarButtonAll.setText("BUSCAR");
        buscarButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonAllActionPerformed(evt);
            }
        });

        textConsultaAll.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        textConsultaAll.setText("Consulta All:");

        textResultados.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        textResultados.setText("RESULTADOS:");

        textBusqueda.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        textBusqueda.setText("Busqueda por ISBN:");

        jScrollPane2.setViewportView(list);

        backButton.setText("VOLVER");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(buscarButtonISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(backButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(buscarButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textConsultaAll))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textResultados)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(textBusqueda)
                    .addContainerGap(598, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(buscarButtonISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(textConsultaAll, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(textBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(407, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonISBNActionPerformed
        // TODO add your handling code here:
        if (!isbn.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "SOLO SE ACEPTA VALOR NUMÉRICO EN EL CAMPO ISBN",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultListModel<String> nuevoModelo = new DefaultListModel<>();
        if (file.length() < 1) {
            nuevoModelo.addElement("ARCHIVO VACIO");
            list.setModel(nuevoModelo);
            list.repaint();
            return;
        } else {
            list.setModel(nuevoModelo);
            list.repaint();
        }
        String date = "null";
        LibroRecetas out = null;
        int isbnIntroducido;
        if (this.isbn.getText().equals("")) {
            isbnIntroducido = 0;
        } else {
            isbnIntroducido = Integer.parseInt(this.isbn.getText());
        }
        switch (typeData) {
            case 'B' -> {
                bLR = new BufferedDAOLibroRecetas(file.getAbsolutePath());
                out = bLR.consultaId(isbnIntroducido);
            }
            case 'D' -> {
                dLR = new BinaryDAOLibroRecetas(file.getAbsolutePath());
                out = dLR.consultaId(isbnIntroducido);
            }
            case 'O' -> {
                oLR = new ObjectDAOLibroRecetas(file.getAbsolutePath());
                out = oLR.consultaId(isbnIntroducido);
            }
            case 'R' -> {
                rLR = new RADAOLibroRecetas(file.getAbsolutePath());
                out = rLR.consultaId(isbnIntroducido);
            }
            case 'X' -> {
                domLR = new DOMDAOLibroRecetas(file.getAbsolutePath());
                out = domLR.consultaId(isbnIntroducido);
            }
        }
        nuevoModelo = new DefaultListModel<>();
        if (out == null) {
            nuevoModelo.addElement("Resultado no encontrado");
        } else {
            nuevoModelo.addElement("Libro Recetas:");
            nuevoModelo.addElement("ISBN: " + out.getIsbn());
            nuevoModelo.addElement("Nombre: " + out.getNombre());
            nuevoModelo.addElement("Número de páginas: " + out.getNumPags());
            if (out.getFechaPublicacion() != null) {
                date = out.getFechaPublicacion().toString();
            }
            nuevoModelo.addElement("Fecha de publicación: " + date);
            nuevoModelo.addElement("Digital: " + out.getDigital());
        }
        list.setModel(nuevoModelo);
        list.repaint();
    }//GEN-LAST:event_buscarButtonISBNActionPerformed

    private void buscarButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonAllActionPerformed
        // TODO add your handling code here:
        ArrayList<LibroRecetas> listaLr = null;
        String date;
        DefaultListModel<String> nuevoModelo = new DefaultListModel<>();
        if (file.length() < 1) {
            nuevoModelo.addElement("ARCHIVO VACIO");
            list.setModel(nuevoModelo);
            list.repaint();
            return;
        } else {
            list.setModel(nuevoModelo);
            list.repaint();
        }
        switch (typeData) {
            case 'B' -> {
                bLR = new BufferedDAOLibroRecetas(file.getAbsolutePath());
                listaLr = bLR.consultaAll();
            }
            case 'D' -> {
                dLR = new BinaryDAOLibroRecetas(file.getAbsolutePath());
                listaLr = dLR.consultaAll();
            }
            case 'O' -> {
                oLR = new ObjectDAOLibroRecetas(file.getAbsolutePath());
                listaLr = oLR.consultaAll();
            }
            case 'R' -> {
                rLR = new RADAOLibroRecetas(file.getAbsolutePath());
                listaLr = rLR.consultaAll();
            }
            case 'X' -> {
                domLR = new DOMDAOLibroRecetas(file.getAbsolutePath());
                listaLr = domLR.consultaAll();
            }
        }
        nuevoModelo.clear();
        if (listaLr == null) {
            nuevoModelo.addElement("No hay elementos o hubo un error");
        } else {
            for (LibroRecetas next : listaLr) {
                date="null";
                nuevoModelo.addElement("Libro Recetas:");
                nuevoModelo.addElement("ISBN: " + next.getIsbn());
                nuevoModelo.addElement("Nombre: " + next.getNombre());
                nuevoModelo.addElement("Número de páginas: " + next.getNumPags());
                if (next.getFechaPublicacion() != null) {
                    date = next.getFechaPublicacion().toString();
                }
                nuevoModelo.addElement("Fecha de publicación: " + date);
                nuevoModelo.addElement("Digital: " + next.getDigital());
                nuevoModelo.addElement("\n");
            }
        }
        list.setModel(nuevoModelo);
        list.repaint();
    }//GEN-LAST:event_buscarButtonAllActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroRecetasRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LibroRecetasRead().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buscarButtonAll;
    private javax.swing.JButton buscarButtonISBN;
    private javax.swing.JTextField isbn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list;
    private javax.swing.JLabel textBusqueda;
    private javax.swing.JLabel textConsultaAll;
    private javax.swing.JLabel textResultados;
    // End of variables declaration//GEN-END:variables
}
