/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adproyecto;

import com.mycompany.adproyecto.libroReceta.LibroRecetasCreate;
import com.mycompany.adproyecto.libroReceta.LibroRecetasDelete;
import com.mycompany.adproyecto.libroReceta.LibroRecetasRead;
import com.mycompany.adproyecto.libroReceta.LibroRecetasUpdate;
import com.mycompany.adproyecto.receta.RecetaCreate;
import com.mycompany.adproyecto.receta.RecetaDelete;
import com.mycompany.adproyecto.receta.RecetaRead;
import com.mycompany.adproyecto.receta.RecetaUpdate;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;



/**
 *
 * @author Vespertino
 */
public class Main extends javax.swing.JFrame {

    File fileReceta;
    File fileLibroReceta;
    BufferedImage icono;

    /**
     * Creates new form Main
     */
    public Main() {
        super("MAIN");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        try {
            icono = ImageIO.read(new File("src\\main\\java\\com\\mycompany\\adproyecto\\icon\\save.png"));
        } catch (IOException e) {
        }

        if (icono != null) {
            setIconImage(icono);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoGuardado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        form_guardado = new javax.swing.JLabel();
        CRUD = new javax.swing.JComboBox<>();
        form_guardado1 = new javax.swing.JLabel();
        tipoTabla = new javax.swing.JComboBox<>();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipoGuardado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BufferedReader/Writer", "DataInputStream/DataOutputStream", "ObjectOutputStream/ObjectInputStream", "RandomAccessFile", "XML" }));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Selecciona que quieres hacer");

        form_guardado.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        form_guardado.setText("Selecciona la forma de guardado que quieras");

        CRUD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Create", "Read", "Update", "Delete" }));

        form_guardado1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        form_guardado1.setText("Selecciona sobre que tabla quieres actuar");

        tipoTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro de recetas", "Receta" }));

        sendButton.setText("ENVIAR");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_guardado1)
                            .addComponent(tipoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_guardado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(form_guardado1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_guardado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        if (CRUD.getSelectedItem().equals("Create")) {
            if (isReceta()) {
                RecetaCreate rCreate=new RecetaCreate();
                rCreate.setVisible(true);
                setVisible(false);
                rCreate.setTypeData(setFileFromTipoGuardado());
                rCreate.setFile(fileReceta);
                rCreate.setFileLr(fileLibroReceta);
                rCreate.setIconImage(icono);
            } else {
                LibroRecetasCreate lrCreate=new LibroRecetasCreate();
                lrCreate.setVisible(true);
                setVisible(false);
                lrCreate.setTypeData(setFileFromTipoGuardado());
                lrCreate.setFile(fileLibroReceta);
                lrCreate.setIconImage(icono);
            }
        } else if (CRUD.getSelectedItem().equals("Read")) {
            if (isReceta()) {
                RecetaRead rRead=new RecetaRead();
                rRead.setVisible(true);
                setVisible(false);
                rRead.setTypeData(setFileFromTipoGuardado());
                rRead.setFile(fileReceta);
                rRead.setIconImage(icono);
            } else {
                LibroRecetasRead lrRead=new LibroRecetasRead();
                lrRead.setVisible(true);
                setVisible(false);
                lrRead.setTypeData(setFileFromTipoGuardado());
                lrRead.setFile(fileLibroReceta);
                lrRead.setIconImage(icono);
            }
        } else if (CRUD.getSelectedItem().equals("Update")) {
            if (isReceta()) {
                RecetaUpdate rUpdate=new RecetaUpdate();
                rUpdate.setVisible(true);
                setVisible(false);
                rUpdate.setTypeData(setFileFromTipoGuardado());
                rUpdate.setFile(fileReceta);
                rUpdate.setFileLr(fileLibroReceta);
                rUpdate.setIconImage(icono);
            } else {
                LibroRecetasUpdate lrUpdate=new LibroRecetasUpdate();
                lrUpdate.setVisible(true);
                setVisible(false);
                lrUpdate.setTypeData(setFileFromTipoGuardado());
                lrUpdate.setFile(fileLibroReceta);
                lrUpdate.setIconImage(icono);
            }
        } else { //Delete
            if (isReceta()) {
                RecetaDelete rDelete=new RecetaDelete();
                rDelete.setVisible(true);
                setVisible(false);
                rDelete.setTypeData(setFileFromTipoGuardado());
                rDelete.setFile(fileReceta);
                rDelete.setIconImage(icono);
            } else {
                LibroRecetasDelete lrDelete=new LibroRecetasDelete();
                lrDelete.setVisible(true);
                setVisible(false);
                lrDelete.setTypeData(setFileFromTipoGuardado());
                lrDelete.setFile(fileLibroReceta);
                lrDelete.setFileR(fileReceta);
                lrDelete.setIconImage(icono);
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    private boolean isReceta() {
        return tipoTabla.getSelectedItem().equals("Receta");
    }

    public char setFileFromTipoGuardado() {
        char retChar;
        if (tipoGuardado.getSelectedItem().equals("BufferedReader/Writer")) {
            fileLibroReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\libroRecetaB.txt");
            fileReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\recetaB.txt");
            retChar= 'B';
        } else if (tipoGuardado.getSelectedItem().equals("DataInputStream/DataOutputStream")) {
            fileLibroReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\libroRecetaD.bin");
            fileReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\recetaD.bin");
            retChar= 'D';
        } else if (tipoGuardado.getSelectedItem().equals("ObjectOutputStream/ObjectInputStream")) {
            fileLibroReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\libroRecetaO.obj");
            fileReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\recetaO.obj");
            retChar= 'O';
        } else if (tipoGuardado.getSelectedItem().equals("RandomAccessFile")) {
            fileLibroReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\libroRecetaR.bin");
            fileReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\recetaR.bin");
            retChar= 'R';
        } else { //XML
            fileLibroReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\libroRecetaX.xml");
            fileReceta = new File("src\\main\\java\\com\\mycompany\\adproyecto\\Files\\recetaX.xml");
            retChar= 'X';
        }
        if (!fileLibroReceta.exists()&&retChar!='X') {
            try {
                fileLibroReceta.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (!fileReceta.exists()&&retChar!='X') {
            try {
                fileReceta.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return retChar;
        
    }
    public File getFileLR(){
        return this.fileLibroReceta;
    }
    
    public File getFileR(){
        return this.fileReceta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CRUD;
    private javax.swing.JLabel form_guardado;
    private javax.swing.JLabel form_guardado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sendButton;
    private javax.swing.JComboBox<String> tipoGuardado;
    private javax.swing.JComboBox<String> tipoTabla;
    // End of variables declaration//GEN-END:variables
}
